// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efhvtoplbytuvhqbgucu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmaHZ0b3BsYnl0dXZocWJndWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjU1NjgsImV4cCI6MjA2NTUwMTU2OH0.DU4DwMru59N_xEclW-SZ6n6xZpjDIsBx4hL9eflwrRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);